### ISSUE TITLE
src/processor.ts:107:12 - error TS2304: Cannot find name 'Store'.

### ISSUE THREAD

**Issue by faisalthaheem** [subsquid/docs#35]
Hey guys, nice documentation, but there is one import missing

On following page, the completed code example before "Apply changes to the Database" 
https://docs.subsquid.io/tutorial/create-a-simple-squid

Should be 
import {SubstrateProcessor, EventHandlerContext, Store} from '@subsquid/substrate-processor'

Instead of
import {SubstrateProcessor, EventHandlerContext} from '@subsquid/substrate-processor'

**Comment by RaekwonIII** [comment]
Hey @faisalthaheem the `Store` interface is needed because it is used in the `getOrCreate` function as you can see here:

```
async function getOrCreate<T extends { id: string }>(
  store: Store,
  entityConstructor: EntityConstructor<T>,
  id: string
): Promise<T> {
  let e = await store.get<T>(entityConstructor, {
    where: { id },
  });

  if (e == null) {
    e = new entityConstructor();
    e.id = id;
  }

  return e;
}
```

If you cannot find it, you may be running an old version of the squid-template, but I cannot say for certain. The point is, in any case: 
* that the `Store` interface is defined in `@subsquid/substrate-processor` so it should be found, if not, there are other issues
* such interface is imported because it is, in fact, used. Removing it would cause other issues.
